[package]
name = "mdbook-blacksmith"
version = "0.1.0"
edition = "2018"
description = "A mdbook preprocessor for generating dynamic content for Rust Forge."
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.1"
log = "0.4.11"
regex = "1.4.1"
reqwest = { version = "0.10", features = ["blocking"] }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.59"
toml = "0.5.7"

[dependencies.clap]
version = "2.33.3"
default-features = false

[dependencies.mdbook]
version = "=0.4.3"
default-features = false
features = ["search"]
