name: Test
on:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.51
      RUN_BLACKSMITH: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install mdbook
        run: curl -sSL https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz
      - name: Install mdbook-linkcheck
        run: cargo install mdbook-linkcheck@0.7.7 --locked
      - name: Check blacksmith format
        run: cargo fmt --check --manifest-path=blacksmith/Cargo.toml
      - name: Build book
        run: ./mdbook build
